dist: xenial
language: bash 
sudo: required

services:
    - docker


install:
  - pip install pycspr
  - pip install -r requirements.txt

# Terraform Plan and Apply
# Plan only on pull requests, Apply on merged code
jobs:
  include:
    - stage: test app
      if: type IN (push)
      script:
        # - python -m pytest -v
    # - stage: master-branch terraform plan
    #   # Only run terraform validate and plan state if within a pull request
    #   if: type IN (pull_request)
    #   script:
    #     - echo "Executing Terraform Plan on pull request code"
    #     - terraform init 
    #     - terraform validate 
    #     - terraform plan 
    # - stage: feature branch terraform plan/apply
    #   if: type IN (push) and branch = feature
    #   script:
    #     - echo "Executing Terraform Plan on pull request code"
    #     - terraform init 
    #     - terraform validate 
    #     - terraform plan 
    # - stage: terraform apply
    #   # Only run terraform apply stage if outside of a pull request
    #   if: type IN (push) and branch = master
    #   script:
    #     - echo "Executing Terraform Apply on merged code"
    #     # ECR Deployment
    #     - sh .travis/deploy_ecr.sh --aws $AWS_ACCOUNT --region $AWS_REGION
    #     - terraform init 
    #     - terraform apply 

# after_success:
#   - sh .travis/deploy_dockerhub.sh
  # Heroku Deployment:
  #- test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh